
FROM node:14


WORKDIR /usr/src/app


COPY package*.json ./

# Install dependencies
RUN npm install

# Bundle app source
COPY . .

# Expose the port the app runs on
EXPOSE 3000


CMD [ "node", "app.js" ]
